forum_homepage:
    path:     /
    defaults: { _controller: ForumBundle:Default:index }
displayforum:
    path:     /displayforum
    defaults: { _controller: ForumBundle:Default:displayforum }
