panier_homepage:
    path:     /
    defaults: { _controller: PanierBundle:Default:index }
displaypanier:
    path:     /displaypanier
    defaults: { _controller: PanierBundle:Default:displaypanier }
